// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATcvoTri9CBcX4RMQgR-Hjx3huWvBuePo',
    appId: '1:1086087840408:web:f2f85ab31ab0fcfaf686ed',
    messagingSenderId: '1086087840408',
    projectId: 'timea-c2ab4',
    authDomain: 'timea-c2ab4.firebaseapp.com',
    storageBucket: 'timea-c2ab4.firebasestorage.app',
    measurementId: 'G-Z7XTDXDSDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxktwCRVEu7_0eItDiEnV7r_R53zZ7Tw',
    appId: '1:1086087840408:android:6219809b8cbe38cdf686ed',
    messagingSenderId: '1086087840408',
    projectId: 'timea-c2ab4',
    storageBucket: 'timea-c2ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa2Td_8ViDkjYJYj7nsfvuudoziHwaWrQ',
    appId: '1:1086087840408:ios:4e9c4737241038d9f686ed',
    messagingSenderId: '1086087840408',
    projectId: 'timea-c2ab4',
    storageBucket: 'timea-c2ab4.firebasestorage.app',
    iosBundleId: 'com.example.timea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa2Td_8ViDkjYJYj7nsfvuudoziHwaWrQ',
    appId: '1:1086087840408:ios:4e9c4737241038d9f686ed',
    messagingSenderId: '1086087840408',
    projectId: 'timea-c2ab4',
    storageBucket: 'timea-c2ab4.firebasestorage.app',
    iosBundleId: 'com.example.timea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATcvoTri9CBcX4RMQgR-Hjx3huWvBuePo',
    appId: '1:1086087840408:web:e7938e572fe7d599f686ed',
    messagingSenderId: '1086087840408',
    projectId: 'timea-c2ab4',
    authDomain: 'timea-c2ab4.firebaseapp.com',
    storageBucket: 'timea-c2ab4.firebasestorage.app',
    measurementId: 'G-DERK4J1HNV',
  );
}
